[package]
name = "gtk-sys"
version = "0.1.3"
authors = ["The Rust-GNOME Project Developers"]
build = "build.rs"
links = "gtk"

description = "FFI bindings to GTK+ 3"
repository = "https://github.com/rust-gnome/gtk"
license = "MIT"
homepage = "https://github.com/rust-gnome/gtk"
documentation = "https://github.com/rust-gnome/gtk"

[lib]
name = "gtk_sys"

[dependencies.glib-sys]
git = "https://github.com/rust-gnome/glib"

[dependencies.gdk-sys]
git = "https://github.com/rust-gnome/gdk"

[dependencies.pango-sys]
git = "https://github.com/rust-gnome/pango"

[dependencies]
libc = "0.1"

[build-dependencies]
pkg-config = "0.3.5"
gcc = "=0.3.9"
