environment:
  matrix:
    - TARGET: i686-pc-windows-gnu
      RUST_VERSION: 1.5.0
      BITS: 32
    - TARGET: x86_64-pc-windows-gnu
      RUST_VERSION: 1.5.0
      BITS: 64
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:RUST_VERSION}-${env:TARGET}.exe"
  - rust-%RUST_VERSION%-%TARGET%.exe /VERYSILENT /NORESTART /COMPONENTS="Rustc,Cargo,Std" /DIR="C:\Rust"
  - SET PATH=C:\Rust\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\usr\bin
  - SET PATH=C:\msys64\mingw%BITS%\bin;C:\msys64\usr\bin;%PATH%
  - if "%BITS%" == "32" pacman --noconfirm -S mingw-w64-i686-gtk3
  - if "%BITS%" == "64" pacman --noconfirm -S mingw-w64-x86_64-gtk3

build_script:
  - rustc -V
  - mkdir .cargo
  - echo paths = ["."] > .cargo\config
  - git clone -q --depth 50 -b pending https://github.com/gtk-rs/examples _examples
  - cd _examples
  - cargo build --features gtk_3_14

test: false
