[options]
girs_dir = "../gir-files"
library = "Gtk"
version = "3.0"
min_cfg_version = "3.4"
target_path = "."
work_mode = "normal"

generate = [
    "Gtk.AccelGroup",
    "Gtk.ActionBar",
    "Gtk.Actionable",
    "Gtk.Adjustment",
    "Gtk.Alignment",
    "Gtk.AppChooserWidget",
    "Gtk.Arrow",
    "Gtk.AspectFrame",
    "Gtk.Bin",
    "Gtk.Box",
    "Gtk.Button",
    "Gtk.ButtonBox",
    "Gtk.Calendar",
    "Gtk.CellAreaBox",
    "Gtk.CellAreaContext",
    "Gtk.CellEditable",
    "Gtk.CellLayout",
    "Gtk.CellRenderer",
    "Gtk.CellRendererText",
    "Gtk.CellRendererToggle",
    "Gtk.CheckButton",
    "Gtk.CheckMenuItem",
    "Gtk.ColorButton",
    "Gtk.ColorChooserWidget",
    "Gtk.Container",
    "Gtk.CssProvider",
    "Gtk.DrawingArea",
    "Gtk.Editable",
    "Gtk.Entry",
    "Gtk.EntryCompletion",
    "Gtk.EventBox",
    "Gtk.Expander",
    "Gtk.FileChooser",
    "Gtk.FileChooserWidget",
    "Gtk.FileFilter",
    "Gtk.Fixed",
    "Gtk.FlowBox",
    "Gtk.FlowBoxChild",
    "Gtk.FontButton",
    "Gtk.FontChooser",
    "Gtk.FontChooserWidget",
    "Gtk.Frame",
    "Gtk.Grid",
    "Gtk.HeaderBar",
    "Gtk.Image",
    "Gtk.InfoBar",
    "Gtk.Label",
    "Gtk.Layout",
    "Gtk.LevelBar",
    "Gtk.LinkButton",
    "Gtk.ListBox",
    "Gtk.ListBoxRow",
    "Gtk.Menu",
    "Gtk.MenuButton",
    "Gtk.MenuItem",
    "Gtk.MenuShell",
    "Gtk.MenuToolButton",
    "Gtk.Misc",
    "Gtk.Notebook",
    "Gtk.Orientable",
    "Gtk.Overlay",
    "Gtk.PageSetup",
    "Gtk.Paned",
    "Gtk.PlacesSidebar",
    "Gtk.Popover",
    "Gtk.PopoverMenu",
    "Gtk.PrintSettings",
    "Gtk.ProgressBar",
    "Gtk.RadioButton",
    "Gtk.Range",
    "Gtk.RecentChooser",
    "Gtk.RecentChooserWidget",
    "Gtk.RecentFilter",
    "Gtk.RecentManager",
    "Gtk.Revealer",
    "Gtk.Scale",
    "Gtk.ScaleButton",
    "Gtk.Scrollable",
    "Gtk.Scrollbar",
    "Gtk.ScrolledWindow",
    "Gtk.SearchBar",
    "Gtk.SearchEntry",
    "Gtk.Separator",
    "Gtk.SeparatorMenuItem",
    "Gtk.SeparatorToolItem",
    "Gtk.SizeGroup",
    "Gtk.SpinButton",
    "Gtk.Spinner",
    "Gtk.Stack",
    "Gtk.StackSwitcher",
    "Gtk.StatusIcon",
    "Gtk.Statusbar",
    "Gtk.Switch",
    "Gtk.TextBuffer",
    "Gtk.TextChildAnchor",
    "Gtk.TextIter",
    "Gtk.TextMark",
    "Gtk.TextTag",
    "Gtk.TextTagTable",
    "Gtk.TextView",
    "Gtk.ToggleButton",
    "Gtk.ToggleToolButton",
    "Gtk.ToolButton",
    "Gtk.ToolItem",
    "Gtk.ToolItemGroup",
    "Gtk.ToolPalette",
    "Gtk.ToolShell",
    "Gtk.Toolbar",
    "Gtk.TreeIter",
    "Gtk.TreeSortable",
    "Gtk.Viewport",
    "Gtk.VolumeButton",
]

ignore = [
    "Gtk.Activatable",
]

manual = [
    "Gdk.Rectangle",
    "Gdk.Screen",
    "Gdk.Window",
    "GdkPixbuf.Pixbuf",
    "GdkPixbuf.PixbufAnimation",
    "Gtk.Buildable",
    "Gtk.Dialog",
    "Gtk.ListStore",
    "Gtk.RecentData",
    "Gtk.RecentInfo",
    "Gtk.TreeModel",
    "Gtk.TreeStore",
    "Gtk.Widget",
    "Gtk.Window",
    "cairo.RectangleInt",
]

[[object]]
name = "Gtk.AppChooserDialog"
status = "generate"
    [[object.function]]
    name = "get_widget"
	[object.function.return]
	nullable = false

[[object]]
name = "Gtk.CellArea"
status = "generate"
    [[object.function]]
    name = "apply_attributes"
    ignore = true
    [[object.function]]
    name = "get_cell_at_position"
    ignore = true
    [[object.function]]
    name = "get_focus_siblings"
    ignore = true

[[object]]
name = "Gtk.ComboBox"
status = "generate"
    [[object.function]]
    name = "set_active_iter"
    ignore = true

[[object]]
name = "Gtk.EntryBuffer"
status = "generate"
    [[object.function]]
    name = "get_text"
	[object.function.return]
	nullable = false

[[object]]
name = "Gtk.IconView"
status = "generate"
    [[object.function]]
    name = "get_cell_rect"
	[[object.function.parameter]]
	name = "path"
	const = true
    [[object.function]]
    name = "get_item_column"
	[[object.function.parameter]]
	name = "path"
	const = true
    [[object.function]]
    name = "get_item_row"
	[[object.function.parameter]]
	name = "path"
	const = true
    [[object.function]]
    name = "item_activated"
	[[object.function.parameter]]
	name = "path"
	const = true
    [[object.function]]
    name = "path_is_selected"
	[[object.function.parameter]]
	name = "path"
	const = true
    [[object.function]]
    name = "scroll_to_path"
	[[object.function.parameter]]
	name = "path"
	const = true
    [[object.function]]
    name = "select_path"
	[[object.function.parameter]]
	name = "path"
	const = true
    [[object.function]]
    name = "set_cursor"
	[[object.function.parameter]]
	name = "path"
	const = true
    [[object.function]]
    name = "set_drag_dest_item"
	[[object.function.parameter]]
	name = "path"
	const = true
    [[object.function]]
    name = "unselect_path"
	[[object.function.parameter]]
	name = "path"
	const = true
    [[object.function]]
    name = "get_selected_items"
    ignore = true

[[object]]
name = "Gtk.TreePath"
status = "generate"
    [[object.function]]
    name = "get_depth"
	[[object.function.parameter]]
	name = "path"
	const = true
    [[object.function]]
    name = "is_ancestor"
	[[object.function.parameter]]
	name = "path"
	const = true
	[[object.function.parameter]]
	name = "descendant"
	const = true
    [[object.function]]
    name = "is_descendant"
	[[object.function.parameter]]
	name = "path"
	const = true
	[[object.function.parameter]]
	name = "ancestor"
	const = true
    [[object.function]]
    name = "get_indices"
    ignore = true
    [[object.function]]
    name = "to_string"
	[[object.function.parameter]]
	name = "path"
	const = true

[[object]]
name = "Gtk.StyleContext"
status = "generate"
    [[object.function]]
    pattern = 'list_.*'
    ignore = true
